version: '3.8'

services:
  backend:
    image: my-app-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev

  frontend:
    image: my-app-frontend:latest
    ports:
      - "80:80"