name: Destroy Infrastructure to AWS

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - infrastructure/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change directory and run Terraform commands
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd Aws-infra
          ls -l  # List contents of infrastructure directory for verification
          pwd    # Print current working directory for verification

          # Set up Terraform with backend configuration
          rm -rf .terraform
          terraform init 

          # Apply Terraform changes and save output to output.json
          terraform apply -auto-approve -json > ../output.json
        

      - name: Upload output.json
        uses: actions/upload-artifact@v2
        with:
          name: terraform-output
          path: output.json