name: Deploy Frontend to AWS

on:
  push:
    # branches:
    #   - main
    # paths:
    #   - frontend/**  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker CLI
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to Docker Hub 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image for frontend
      - name: Build and push frontend Docker image
        env:
          TAG: ${{ github.sha }}
        run: | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ secrets.TAG }} -f frontend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ secrets.TAG }}

      # SSH into frontend EC2 instance and deploy the frontend container
      - name: Deploy frontend to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONTEND_EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker stop frontend || true
            sudo docker rm frontend || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:${{ secrets.TAG }}
            sudo docker run -d -p 80:80 --name frontend ${{ secrets.DOCKER_USERNAME }}/frontend:${{ secrets.TAG }}
