name: Deploy Infrastructure to Azure

on:
  workflow_dispatch:  # Manual trigger
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - infrastructure/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change directory and run Terraform commands
        run: |
          cd Azure-infra
          ls -l  # List contents of infrastructure directory for verification
          pwd    # Print current working directory for verification

          # Set up Terraform with Azure backend configuration
          rm -rf .terraform
          terraform init -backend-config="client_id=${ARM_CLIENT_ID}" -backend-config="client_secret=${ARM_CLIENT_SECRET}" -backend-config="subscription_id=${ARM_SUBSCRIPTION_ID}" -backend-config="tenant_id=${ARM_TENANT_ID}"

          # Apply Terraform changes
          terraform destroy -auto-approve

      - name: Upload Terraform state file
        uses: actions/upload-artifact@v2
        with:
          name: terraform-state
          path: infrastructure/terraform.tfstate