name: Deploy Infrastructure to Azure

on:
  workflow_dispatch:  # Manual trigger
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - infrastructure/**

  
jobs:
  deploy:
    runs-on: ubuntu-latest

    # env:
    #   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    #   AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    #   AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Change directory and run Terraform commands
        run: |
          cd Azure-infra
          ls -l  # List contents of infrastructure directory for verification
          pwd    # Print current working directory for verification

          # Set up Terraform with Azure backend configuration
          rm -rf .terraform
          # terraform init 

          # Apply Terraform changes
          terraform apply -auto-approve

      - name: Upload Terraform state file
        uses: actions/upload-artifact@v2
        with:
          name: terraform-state
          path: Azure-infra/terraform.tfstate
