name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change directory and run Terraform commands
        run: |
          cd infrastructure
          ls -l  # List contents of infrastructure directory for verification
          pwd    # Print current working directory for verification
          # Set up Terraform
          terraform init
          # Apply Terraform changes
          terraform apply -auto-approve > ../output.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}