name: Terraform

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - infrastructure/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change directory and run Terraform commands
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
        run: |
          cd infrastructure
          ls -l  # List contents of infrastructure directory for verification
          pwd    # Print current working directory for verification

          # Set up Terraform with backend configuration
          rm -rf .terraform
          terraform init -backend-config=pipeline.tfvars -upgrade=true -no-color -input=false

          # Apply Terraform changes and save output to output.json
          terraform destroy -auto-approve -json > ../destroy.json
        

      - name: Upload destroy.json
        uses: actions/upload-artifact@v2
        with:
          name: terraform-destroy
          path: destroy.json