name: Deploy Application

on:
  push:
    branches:
      - main
    paths:
      - frontend/**  # This ensures the pipeline runs when any file in the frontend directory changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker CLI
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to Docker Hub or another registry where you push images
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image for frontend
      - name: Build and push frontend Docker image
        env:
          TAG: ${{ github.sha }}
        run: |
          cd frontend  
          docker build -t obifrankie/frontend:$TAG .
          docker push obifrankie/frontend:$TAG

      # SSH into your frontend EC2 instance and deploy the frontend container
      - name: Deploy frontend to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONTEND_EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop frontend || true
            docker rm frontend || true
            docker pull your-dockerhub-username/frontend:$TAG
            docker run -d -p 80:80 --name frontend your-dockerhub-username/frontend:$TAG
